# Generated by Django 6.0.4 on 2026-04-14 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('origen', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('URGENCIAS', 'Urgencias')], max_length=20)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('EN_PREPARACION', 'En preparación'), ('EN_CIRUGIA', 'En cirugía'), ('EN_RECUPERACION', 'En recuperación'), ('FINALIZADO', 'Finalizado'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcionOtro', models.CharField(blank=True, max_length=50, null=True)),
                ('ingresadoEn', models.DateTimeField(auto_now_add=True)),
                ('actualizadoEn', models.DateTimeField(auto_now=True)),
                ('oculto', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_core.paciente')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
        migrations.CreateModel(
            name='RegistroEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estadoAnterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estadoNuevo', models.CharField(max_length=20)),
                ('cambiadoEn', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_core.sesion')),
            ],
            options={
                'db_table': 'registro_estados',
            },
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['oculto', 'ingresadoEn'], name='sesiones_oculto_dd592e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesion',
            constraint=models.UniqueConstraint(condition=models.Q(('oculto', False)), fields=('paciente',), name='unique_active_session_per_patient'),
        ),
    ]
