# Generated by Django 6.0.4 on 2026-04-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_sesion_labelotro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_core.paciente'),
        ),
    ]
