# Generated by Django 6.0.4 on 2026-04-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_eliminar_registroestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_core.paciente'),
            preserve_default=False,
        ),
    ]
